[webservers]
srv-web-01 ansible_host=10.10.10.20

[control]
srv-ansible-01 ansible_host=10.10.10.30

[linux:children]
webservers
control

[linux:vars]
ansible_user=kevin
ansible_python_interpreter=/usr/bin/python3
